version: '3.8'

services:
  fx-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    image: analyze-fx:latest
    container_name: fx-analyzer
    env_file:
      - .env
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - fx-network

networks:
  fx-network:
    driver: bridge