#!/bin/bash
# 複数通貨ペア分析の手動実行スクリプト

echo "=== 複数通貨ペア分析 (USD/JPY, XAU/USD, BTC/USD) ==="
echo "実行時刻: $(date '+%Y-%m-%d %H:%M:%S JST')"
echo ""
echo "以下のコマンドを実行してください:"
echo ""
echo "1. 通常実行:"
echo "   cd /Users/shinzato/programing/claude_code/analyze_FX_chart"
echo "   ./venv/bin/python run_multi_currency.py"
echo ""
echo "2. デバッグモード実行:"
echo "   cd /Users/shinzato/programing/claude_code/analyze_FX_chart"
echo "   ./venv/bin/python run_multi_currency.py --debug"
echo ""
echo "3. 設定確認のみ:"
echo "   cd /Users/shinzato/programing/claude_code/analyze_FX_chart"
echo "   ./venv/bin/python test_currency_setup.py"
echo ""
echo "実行後、以下を確認してください:"
echo "- Notionデータベースで Currency フィールドによるフィルタリング"
echo "- analysis_summary.md ファイルの生成"
echo "- screenshots/ ディレクトリ内の各通貨ペアのチャート画像"